FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:15.10-buster

RUN install_packages gcc g++ python3 udev build-essential
ENV UDEV=1

WORKDIR /usr/src/app
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm ci --only=production

COPY src/ ./
CMD ["node", "/usr/src/app/main.js"]