version: '2.1'
networks: {}
services:
  weatherStationCoreLink:
    build: ./WeatherStationCoreLink
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: false
    restart: always
    network_mode: host
    labels:
      io.resin.features.resin-api: '1'
      io.resin.update.strategy: download-then-kill
      io.resin.update.handover-timeout: ''