FROM resin/%%RESIN_MACHINE_NAME%%-debian

 RUN apt-get update && apt-get install -yq \
    libpng-dev \
    libfreetype6-dev \
    pkg-config \
    build-essential \
    curl \
    manpages-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-tk \
    python3-pip \
    libfreetype6-dev \
    rpl \
    git \
    nano

RUN pip install setuptools pyserial pusher
#pip also install -         git+https://github.com/resin-io/resin-sdk-python.git

# Set our working directory
WORKDIR /usr/src/app

# switch on systemd init system in container
#ENV INITSYSTEM on



# This will copy all files in our root to the working  directory in the container
COPY . ./

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# main.py will run when container starts up on the device
CMD ["bash","/usr/src/app/start.sh"]
