version: '2.1'
networks: {}
services:
  weatherStationCoreLink:
    build: ./WeatherStationCoreLink
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
  internetPowerMonitoring:
    build: ./InternetAndPowerMonitoring
    ports:
      - "80:80"
    restart: always