version: '2.1'
networks: {}
services:
  weatherStationCoreLink:
    build:
      context: ./WeatherStationCoreLink
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
      io.resin.update.strategy: download-then-kill
      io.resin.update.handover-timeout: ''