version: '2.1'
volumes:
    resin-data:
services:
  serialConnectoin:
    build: ./serialConnection
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    labels:
      - io.balena.features.supervisor-api: '1'