on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Push new Version to Balena Cloud
jobs:
  balenapush:
    name: Push to Balena.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: ${{ secrets.BALENA_APPLICATION_NAME }}
          create_tag: false
