# base-image for python on any machine using a template variable,
# see more about dockerfile templates here:http://docs.resin.io/pages/deployment/docker-templates
FROM resin/%%RESIN_MACHINE_NAME%%-python

# Set our working directory
WORKDIR /usr/src/app

# pip install python deps from requirements.txt on the resin.io build server
RUN pip install Flask==0.10.1

# This will copy all files in our root to the working  directory in the container
COPY . ./

# main.py will run when container starts up on the device
CMD ["python","main.py"]